GROQ_API_KEY ="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"
HF_API_KEY ="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"
ANTHROPIC_API_KEY ="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"
AZURE_OPENAI_KEY ="gpt-4o"
OPENAI_API_KEY = "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
