GROQ_API_KEY ="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"
HF_API_KEY ="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"
ANTHROPIC_API_KEY ="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"
AZURE_OPENAI_KEY ="gpt-4o"
OPENAI_API_KEY = "sk-...sjcA"

