GROQ_API_KEY ="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"
HF_API_KEY ="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"
OPENAI_API_KEY ="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 "
ANTHROPIC_API_KEY ="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"
AZURE_OPENAI_KEY ="gpt-4o"
